web:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ../database_srcs/:/code
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx.conf:/usr/local/etc/php/conf.d/nginx.conf
  links:
    - php

php:
  image: some-content-nginx
  environment:
    - DIR_PATH=/data/files/
  volumes:
    - ../database_srcs/:/code
    - ../data:/data